# Generated by Django 5.2.16 on 2026-07-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('kind', models.CharField(choices=[('hotline_xml', 'Hotline XML')], db_index=True, max_length=16, verbose_name='Тип')),
                ('file', models.FileField(upload_to='feeds/', verbose_name='Файл')),
                ('items_count', models.IntegerField(default=0, verbose_name='Товарів у фіді')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Пропущено')),
                ('skipped_reasons', models.JSONField(blank=True, default=dict, verbose_name='Причини пропуску')),
                ('no_mpn_count', models.IntegerField(default=0, verbose_name='Без артикула виробника')),
                ('default_dims_count', models.IntegerField(default=0, verbose_name='Товарів на дефолтних габаритах')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Розмір, байт')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Згенеровано')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тривалість, мс')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Поточний')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_artifacts', to='sync.syncrun')),
            ],
            options={
                'verbose_name': 'Артефакт фіда',
                'verbose_name_plural': 'Артефакти фідів',
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['kind', '-generated_at'], name='feed_kind_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('kind',), name='uniq_current_feed')],
            },
        ),
        migrations.CreateModel(
            name='HotlineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('path', models.CharField(max_length=500, unique=True, verbose_name='Шлях')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('depth', models.PositiveSmallIntegerField(default=0, verbose_name='Глибина')),
                ('is_leaf', models.BooleanField(db_index=True, default=False, verbose_name='Листова')),
                ('last_seen_run', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Останній прогін')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feeds.hotlinecategory')),
            ],
            options={
                'verbose_name': 'Категорія Hotline',
                'verbose_name_plural': 'Рубрикатор Hotline',
                'ordering': ('path',),
                'indexes': [models.Index(fields=['is_leaf', 'is_active'], name='hl_cat_leaf_idx'), models.Index(fields=['parent', 'name'], name='hl_cat_parent_idx')],
            },
        ),
    ]
