# Generated by Django 5.2.16 on 2026-07-13 13:39

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('feeds', '0001_initial'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hotline_category',
            field=models.ForeignKey(blank=True, help_text='LEAF-вузол рубрикатора Hotline. Порожньо → товари категорії у фід НЕ йдуть (лічильник no_hotline_category у FeedArtifact.skipped_reasons).', limit_choices_to={'is_active': True, 'is_leaf': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_categories', to='feeds.hotlinecategory', verbose_name='Категорія Hotline'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='Батьківська категорія'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='У яких категоріях показувати/фільтрувати. Порожньо = у всіх.', related_name='attributes', to='catalog.category', verbose_name='Категорії'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aliases'], name='country_aliases_gin'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.syncrun'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sync.pricesource', verbose_name='Прайс-джерело'),
        ),
        migrations.AddField(
            model_name='product',
            name='winning_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sync.supplieroffer', verbose_name='Оффер-переможець'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalog.attributeoption'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='relatedgroupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.relatedgroup'),
        ),
        migrations.AddField(
            model_name='relatedgroupitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_memberships', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aliases'], name='unit_aliases_gin'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='catalog.unit', verbose_name='Одиниця'),
        ),
        migrations.AddField(
            model_name='variantgroup',
            name='axis_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_groups', to='catalog.attribute', verbose_name='Вісь перемикача'),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.variantgroup'),
        ),
        migrations.AddField(
            model_name='variantitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_memberships', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='attributeoption',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aliases'], name='attropt_aliases_gin'),
        ),
        migrations.AddConstraint(
            model_name='attributeoption',
            constraint=models.UniqueConstraint(fields=('attribute', 'slug'), name='uniq_attr_option'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='cat_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'depth'], name='cat_active_depth_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='cat_path_btree'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug_uk'), name='uniq_cat_slug_in_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', 'availability'], name='prod_list_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', 'price'], name='prod_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['hotline_enabled', 'is_active'], name='prod_hotline_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source_currency', 'price_locked'], name='prod_usd_recalc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_source', 'availability'], name='prod_deactivate_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('denorm_dirty', True)), fields=['denorm_dirty'], name='prod_dirty_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('name_normalized', ''), _negated=True), fields=['name_normalized'], name='prod_name_norm_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filter_tokens'], name='prod_filter_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_uk'], name='prod_fts_uk_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_ru'], name='prod_fts_ru_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_uk'], name='prod_name_uk_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ru'], name='prod_name_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='prod_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='prod_base_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability', 'on_order'), _negated=True), ('order_lead_days__isnull', False), _connector='OR'), name='prod_on_order_needs_lead_days'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('old_price__isnull', True), ('old_price__gt', models.F('price')), _connector='OR'), name='prod_old_price_gt_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_currency', 'USD'), _negated=True), ('usd_rate_used__isnull', False), _connector='OR'), name='prod_usd_needs_rate'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', '-changed_at'], name='ph_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['product', 'attribute'], name='pav_card_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'value_number', 'product'], name='pav_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(condition=models.Q(('option__isnull', False)), fields=('product', 'attribute', 'option'), name='uniq_pav_option'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(condition=models.Q(('option__isnull', True)), fields=('product', 'attribute'), name='uniq_pav_scalar'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'source', 'last_seen_run'], name='img_sync_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url_hash', ''), _negated=True), fields=('product', 'source_url_hash'), name='uniq_product_image_url'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='uniq_main_image'),
        ),
        migrations.AddIndex(
            model_name='relatedgroupitem',
            index=models.Index(fields=['product', 'group'], name='relgroup_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='relatedgroupitem',
            constraint=models.UniqueConstraint(fields=('group', 'product'), name='uniq_group_product'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aliases'], name='attr_aliases_gin'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('filter_widget', 'range_buckets'), _negated=True), models.Q(('range_buckets', []), _negated=True), _connector='OR'), name='attr_buckets_required_for_range'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(condition=models.Q(('role', ''), _negated=True), fields=('role',), name='uniq_attr_role'),
        ),
        migrations.AddIndex(
            model_name='variantitem',
            index=models.Index(fields=['group', 'sort_order'], name='variant_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantitem',
            constraint=models.UniqueConstraint(fields=('group', 'product'), name='uniq_variant_member'),
        ),
    ]
