# Generated by Django 5.2.16 on 2026-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_price_trigger_to_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_incomplete',
            field=models.BooleanField(db_index=True, default=False, help_text="Немає артикула та/або фото в прайсі. Такий товар СХОВАНО з сайту (is_active=False): це рядок-чернетка, який замовник ще заповнює. Щойно в прайсі з'являться артикул І фото — наступний синк зніме прапорець і покаже товар САМ.", verbose_name='Неповний товар (чернетка прайсу)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku_is_surrogate',
            field=models.BooleanField(db_index=True, default=False, help_text='У прайсі в колонці «Артикул» стоїть «Уточнюється» → синк згенерував сурогатний ключ AUTO-xxxxxxxxxxxx з нормалізованої назви. Щойно замовник впише справжній артикул, синк оновить sku ЦЬОМУ Ж товару (зіставлення за name_normalized), а не створить другий.', verbose_name='Артикул сурогатний'),
        ),
    ]
