# Generated by Django 5.2.16 on 2026-07-20 19:18

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_incomplete_product_sku_is_surrogate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, help_text='Маленький значок біля назви групи в меню каталогу. Показується в круглій рамці, тому картинка має бути КВАДРАТНА (наприклад 64×64) і на ПРОЗОРОМУ фоні — інакше по кутах буде видно білий квадрат. Формати: SVG (найкраще), PNG або WebP. Розмір файла — до 64 КБ: емблеми всіх категорій вантажаться разом.', upload_to='categories/icons/', validators=[catalog.validators.validate_icon], verbose_name='Міні-емблема'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Велике горизонтальне фото групи для плиток на головній сторінці. Пропорції приблизно 3:2 (наприклад 900×600), формат JPG, PNG або WebP. Це НЕ значок у меню — для меню є «Міні-емблема» вище.', upload_to='categories/tiles/', verbose_name='Плитка'),
        ),
    ]
