# Generated by Django 5.2.16 on 2026-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_media_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_quick_nav',
            field=models.BooleanField(default=False, help_text='Вузький рядок посилань одразу під логотипом. Раніше туди автоматично падали ВСІ кореневі категорії — замовник попросив натомість обирати окремі. Порядок — за полем «Порядок». Нічого не відмічено → рядка на сайті немає взагалі. ⚠️ Категорія без товарів не показується ніде, зокрема й тут.', verbose_name='Показувати в рядку під шапкою'),
        ),
    ]
