# Generated by Django 5.2.16 on 2026-07-13 13:39

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('number', models.CharField(max_length=24, unique=True, verbose_name='Номер')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публічний токен')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('confirmed', 'Підтверджений'), ('packed', 'Скомплектований'), ('shipped', 'Відправлений'), ('delivered', 'Доставлений'), ('done', 'Завершений'), ('cancelled', 'Скасований'), ('returned', 'Повернення')], db_index=True, default='new', max_length=12, verbose_name='Статус')),
                ('idempotency_key', models.UUIDField(unique=True, verbose_name='Ключ ідемпотентності')),
                ('last_name', models.CharField(max_length=80, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=80, verbose_name="Ім'я")),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар покупця')),
                ('delivery_method', models.CharField(choices=[('np_warehouse', 'Відділення Нової Пошти'), ('np_postomat', 'Поштомат Нової Пошти'), ('np_courier', "Кур'єр Нової Пошти"), ('pickup', 'Самовивіз (Ужгород)'), ('local_courier', "Кур'єр по Ужгороду")], max_length=14, verbose_name='Спосіб доставки')),
                ('np_area_ref', models.CharField(blank=True, max_length=36, verbose_name='НП: область (ref)')),
                ('np_area_name', models.CharField(blank=True, max_length=120, verbose_name='НП: область')),
                ('np_city_ref', models.CharField(blank=True, max_length=36, verbose_name='НП: місто (ref)')),
                ('np_settlement_ref', models.CharField(blank=True, max_length=36, verbose_name='НП: населений пункт (ref)')),
                ('np_city_name', models.CharField(blank=True, max_length=200, verbose_name='НП: місто')),
                ('np_warehouse_ref', models.CharField(blank=True, max_length=36, verbose_name='НП: відділення (ref)')),
                ('np_warehouse_name', models.CharField(blank=True, max_length=255, verbose_name='НП: відділення')),
                ('np_service_type', models.CharField(blank=True, max_length=24, verbose_name='НП: тип послуги')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адреса доставки')),
                ('delivery_cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Орієнтовна вартість доставки')),
                ('ttn', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='ТТН')),
                ('payment_method', models.CharField(choices=[('cod', 'Накладений платіж'), ('prepay', 'Повна передоплата (реквізити)'), ('online', 'Онлайн-оплата картою'), ('installment', 'Оплата частинами')], max_length=12, verbose_name='Спосіб оплати')),
                ('payment_status', models.CharField(choices=[('not_required', 'Не потрібна'), ('pending', 'Очікує'), ('paid', 'Оплачено'), ('failed', 'Помилка'), ('refunded', 'Повернуто')], db_index=True, default='not_required', max_length=12, verbose_name='Статус оплати')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено о')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума товарів')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Знижка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='До сплати')),
                ('manager_note', models.TextField(blank=True, verbose_name='Примітка менеджера')),
                ('utm', models.JSONField(blank=True, default=dict, verbose_name='UTM')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cms.pickuppoint', verbose_name='Пункт самовивозу')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна за одиницю')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума позиції')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Фото')),
                ('installment_available', models.BooleanField(default=False, verbose_name='Доступна оплата частинами')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Вага (ефективна)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name="Об'єм (ефективний)")),
                ('dims_source', models.CharField(blank=True, max_length=10, verbose_name='Джерело габаритів')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12, verbose_name='Зі статусу')),
                ('to_status', models.CharField(max_length=12, verbose_name='У статус')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Змінив')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Історія статусів',
                'verbose_name_plural': 'Історія статусів',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='order_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_method__in', ['np_warehouse', 'np_postomat']), _negated=True), models.Q(('np_city_ref__gt', ''), ('np_warehouse_ref__gt', '')), _connector='OR'), name='order_np_refs_required'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method__in', ['online', 'installment']), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='order_online_needs_email'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='oi_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='oi_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')))), name='oi_line_total_matches'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', '-created_at'], name='osh_order_idx'),
        ),
    ]
