# Generated by Django 5.2.16 on 2026-07-13 13:39

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ⚠️ РУЧНЕ РЕБРО (як і в catalog/0001_initial): delivery не має жодного FK за межі
        #    застосунку, тож автодетектор лишає dependencies порожнім — і на чистій БД
        #    GinIndex(present gin_trgm_ops) на NPSettlement падає з
        #        operator class "gin_trgm_ops" does not exist.
        #    Розширення живуть у core/0001_extensions (ADR-022).
        ("core", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name='NPArea',
            fields=[
                ('ref', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='Ref НП')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('center_city_ref', models.CharField(blank=True, max_length=36, verbose_name='Ref обласного центру')),
            ],
            options={
                'verbose_name': 'Область (НП)',
                'verbose_name_plural': 'Області (НП)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryQuote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=140, verbose_name='Ключ кешу')),
                ('city_ref', models.CharField(max_length=36, verbose_name='CityRef отримувача')),
                ('service_type', models.CharField(choices=[('WarehouseWarehouse', 'Відділення → Відділення'), ('WarehousePostomat', 'Відділення → Поштомат'), ('WarehouseDoors', "Відділення → Двері (кур'єр)")], max_length=24, verbose_name='ServiceType')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Вага (ефективна), кг')),
                ('volume_m3', models.DecimalField(decimal_places=5, max_digits=10, verbose_name="Об'єм (ефективний), м³")),
                ('cost_declared', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Оголошена вартість')),
                ('cost_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість доставки')),
                ('cost_redelivery', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зворотна доставка грошей')),
                ('dims_source', models.CharField(blank=True, choices=[('spec', 'Характеристики товару'), ('product', 'Поля товару (ручний override)'), ('category', 'Дефолт категорії'), ('default', 'Глобальний дефолт')], max_length=10, verbose_name='Джерело габаритів')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Сира відповідь НП')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Розрахунок доставки',
                'verbose_name_plural': 'Розрахунки доставки',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['city_ref', '-created_at'], name='quote_city_idx')],
            },
        ),
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('ref', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='CityRef (канон)')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('settlement_type', models.CharField(blank=True, max_length=60, verbose_name='Тип населеного пункту')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активне')),
                ('last_seen_run', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Останній прогін')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='delivery.nparea')),
            ],
            options={
                'verbose_name': 'Місто (НП)',
                'verbose_name_plural': 'Міста (НП)',
            },
        ),
        migrations.CreateModel(
            name='NPSettlement',
            fields=[
                ('ref', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='SettlementRef')),
                ('delivery_city_ref', models.CharField(db_index=True, max_length=36, verbose_name='DeliveryCity ref (канон для API)')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('present', models.CharField(max_length=255, verbose_name='Рядок для дропдауна')),
                ('settlement_type_code', models.CharField(blank=True, max_length=16, verbose_name='Код типу (м./с./смт)')),
                ('warehouses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Відділень (наших)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
                ('last_seen_run', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Останній прогін')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='delivery.nparea')),
            ],
            options={
                'verbose_name': 'Населений пункт (НП)',
                'verbose_name_plural': 'Населені пункти (НП)',
            },
        ),
        migrations.CreateModel(
            name='NPWarehouse',
            fields=[
                ('ref', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='Ref НП')),
                ('city_ref', models.CharField(db_index=True, max_length=36, verbose_name='CityRef')),
                ('settlement_ref', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='SettlementRef')),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('description', models.CharField(max_length=300, verbose_name='Опис')),
                ('short_address', models.CharField(blank=True, max_length=200, verbose_name='Коротка адреса')),
                ('category', models.CharField(choices=[('Branch', 'Відділення'), ('Postomat', 'Поштомат'), ('DropOff', 'Пункт видачі')], db_index=True, max_length=10, verbose_name='Тип')),
                ('type_ref', models.CharField(blank=True, max_length=36, verbose_name='TypeOfWarehouse ref')),
                ('place_max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Макс. вага місця, кг')),
                ('max_width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Макс. ширина, см')),
                ('max_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Макс. висота, см')),
                ('max_length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Макс. довжина, см')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='WarehouseStatus')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активне')),
                ('last_seen_run', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Останній прогін')),
                ('city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='delivery.npcity')),
            ],
            options={
                'verbose_name': 'Відділення (НП)',
                'verbose_name_plural': 'Відділення (НП)',
                'ordering': ('city_ref', 'category', 'number'),
            },
        ),
        migrations.AddIndex(
            model_name='npcity',
            index=models.Index(fields=['area', 'name'], name='np_city_area_idx'),
        ),
        migrations.AddIndex(
            model_name='npsettlement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['present'], name='np_settl_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='npsettlement',
            index=models.Index(fields=['area', 'name'], name='np_settl_area_idx'),
        ),
        migrations.AddIndex(
            model_name='npsettlement',
            index=models.Index(fields=['is_active', '-warehouses_count'], name='np_settl_active_idx'),
        ),
        migrations.AddIndex(
            model_name='npwarehouse',
            index=models.Index(fields=['city_ref', 'category', 'is_active'], name='np_wh_city_idx'),
        ),
        migrations.AddIndex(
            model_name='npwarehouse',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='np_wh_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
