# Generated by Django 5.2.16 on 2026-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npwarehouse',
            name='category',
            field=models.CharField(choices=[('Branch', 'Відділення'), ('Postomat', 'Поштомат'), ('DropOff', 'Пункт видачі'), ('Fulfillment', 'Фулфілмент')], db_index=True, max_length=20, verbose_name='Тип'),
        ),
    ]
