# Generated by Django 5.2.16 on 2026-07-16 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_product_is_incomplete_product_sku_is_surrogate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecHarvestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('category_key', models.CharField(default='dishwasher', help_text='Ключ у aispecs.category_specs.TEMPLATES — за ним мапляться характеристики.', max_length=40, verbose_name='Шаблон категорії')),
                ('status', models.CharField(choices=[('queued', 'У черзі'), ('running', 'Виконується'), ('needs_review', 'На перегляд'), ('applied', 'Застосовано'), ('rejected', 'Відхилено'), ('failed', 'Помилка')], db_index=True, default='needs_review', max_length=16, verbose_name='Статус')),
                ('model_code', models.CharField(blank=True, max_length=120, verbose_name='Код моделі')),
                ('matched', models.BooleanField(default=False, verbose_name='Точний збіг коду')),
                ('match_confidence', models.CharField(blank=True, choices=[('high', 'Висока'), ('medium', 'Середня'), ('low', 'Низька')], max_length=8, verbose_name='Впевненість збігу')),
                ('source_type', models.CharField(blank=True, max_length=20, verbose_name='Тип джерела')),
                ('primary_source_url', models.URLField(blank=True, max_length=1000, verbose_name='Головне джерело')),
                ('proposed_specs', models.JSONField(blank=True, default=list, verbose_name='Запропоновані характеристики')),
                ('proposed_programs', models.JSONField(blank=True, default=list, verbose_name='Перелік програм')),
                ('proposed_description', models.TextField(blank=True, verbose_name='Запропонований опис')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Застереження збирача')),
                ('applied_count', models.PositiveSmallIntegerField(default=0, verbose_name='Записано полів')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Переглянуто')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_jobs', to='catalog.product', verbose_name='Товар')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Переглянув')),
            ],
            options={
                'verbose_name': 'ШІ-збір характеристик',
                'verbose_name_plural': 'ШІ-збір характеристик',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='harvest_status_idx')],
            },
        ),
    ]
