# Generated by Django 5.2.16 on 2026-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home_slider', 'Слайдер головної'), ('home_promo', 'Промо-блок головної'), ('home_side', 'Реклама праворуч від каталогу (головна)'), ('category_top', 'Банер над категорією')], db_index=True, max_length=16, verbose_name='Розміщення'),
        ),
    ]
