# Generated by Django 5.2.16 on 2026-07-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_media_help_text'),
        ('cms', '0002_alter_banner_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Потрібна ТІЛЬКИ для розміщення «Банер над категорією». Для банерів головної залиште порожнім.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категорія'),
        ),
    ]
