# Generated by Django 5.2.16 on 2026-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_banner_category_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='focal_point',
            field=models.CharField(choices=[('center', 'По центру'), ('top', 'Верх'), ('bottom', 'Низ'), ('left', 'Ліворуч'), ('right', 'Праворуч'), ('top left', 'Верх ліворуч'), ('top right', 'Верх праворуч'), ('bottom left', 'Низ ліворуч'), ('bottom right', 'Низ праворуч')], default='center', help_text="Слот майже завжди інших пропорцій, ніж картинка, тому вона обрізається. Тут вибирається, яку частину НЕ обрізати — прев'ю показує результат одразу.", max_length=16, verbose_name='Що лишати в кадрі'),
        ),
    ]
