# Generated by Django 5.2.16 on 2026-07-22 12:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# Пресети старого `focal_point` → відсотки нового кадру.
_FOCAL_TO_PERCENT = {
    "center": (50, 50),
    "top": (50, 0),
    "bottom": (50, 100),
    "left": (0, 50),
    "right": (100, 50),
    "top left": (0, 0),
    "top right": (100, 0),
    "bottom left": (0, 100),
    "bottom right": (100, 100),
}


def migrate_data_forward(apps, schema_editor):
    """Переносить дані ПЕРЕД тим, як зникнуть старі поля й варіанти.

    ⚠️ Без цього кроку міграція мовчки псує контент:
      • банери зі знесеним `home_slider` лишились би з невалідним розміщенням і
        зникли б з адмінки (у формі такого варіанта більше немає);
      • `category_top` фронт і так не виводив — деактивуємо, щоб не висіли «активними»
        назавжди невидимими;
      • обраний кадр (`focal_point`) інакше скинувся б у центр у всіх банерів.
    """
    Banner = apps.get_model("cms", "Banner")

    for banner in Banner.objects.all():
        x, y = _FOCAL_TO_PERCENT.get(getattr(banner, "focal_point", "") or "center", (50, 50))
        updates = {"focus_x": x, "focus_y": y}

        if banner.placement == "home_slider":
            # Слайдера ніколи не існувало — такий банер і так падав у промо-слот.
            updates["placement"] = "home_promo"
        elif banner.placement == "category_top":
            # Сайт це розміщення не читав: банер був «активним» і невидимим.
            updates["placement"] = "home_promo"
            updates["is_active"] = False

        Banner.objects.filter(pk=banner.pk).update(**updates)


def migrate_data_backward(apps, schema_editor):
    """Назад точно не відновиш: `home_slider` і `category_top` уже злиті в `home_promo`.
    Лишаємо no-op, щоб міграція була оборотною за схемою, але без вигаданих даних."""


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_media_help_text'),
        ('cms', '0004_banner_focal_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='focus_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='0 — лівий край, 100 — правий. Простіше: клікніть по картинці в схемі.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Кадр по горизонталі, %'),
        ),
        migrations.AddField(
            model_name='banner',
            name='focus_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='0 — верх, 100 — низ.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Кадр по вертикалі, %'),
        ),
        migrations.AddField(
            model_name='banner',
            name='zoom',
            field=models.PositiveSmallIntegerField(default=100, help_text='100 — вписати як є. Більше — наблизити (обріже сильніше).', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)], verbose_name='Масштаб, %'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Не використовується: розміщення «над категорією» прибрано.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категорія'),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
        migrations.RemoveField(
            model_name='banner',
            name='focal_point',
        ),
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home_promo', 'Головна: банер біля каталогу (до 3 в ряд)'), ('home_side', 'Головна: вузька реклама у відкритому каталозі')], db_index=True, max_length=16, verbose_name='Розміщення'),
        ),
    ]
