# Generated by Django 5.2.16 on 2026-07-13 13:39

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('attribute', 'Характеристики'), ('value', 'Значення'), ('unit', 'Одиниці виміру'), ('category', 'Категорії'), ('general', 'Загальне')], db_index=True, default='general', max_length=12, verbose_name='Розділ')),
                ('source_lang', models.CharField(default='uk', max_length=5, verbose_name='Мова джерела')),
                ('target_lang', models.CharField(default='ru', max_length=5, verbose_name='Цільова мова')),
                ('source_term', models.CharField(max_length=200, verbose_name='Термін (uk)')),
                ('target_term', models.CharField(max_length=200, verbose_name='Переклад (ru)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примітка')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Термін глосарія',
                'verbose_name_plural': 'Глосарій',
                'ordering': ('section', 'sort_order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'section'], name='gloss_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('source_term'), models.F('source_lang'), models.F('target_lang'), name='uniq_glossary_term')],
            },
        ),
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name="ID об'єкта")),
                ('field', models.CharField(max_length=64, verbose_name='Поле')),
                ('kind', models.CharField(choices=[('attribute_name', 'Назва характеристики'), ('attribute_value', 'Значення характеристики'), ('unit', 'Одиниця виміру'), ('category_name', 'Назва категорії'), ('product_name', 'Назва товару'), ('product_short_desc', 'Короткий опис товару'), ('product_description', 'Опис товару (HTML)'), ('seo_title', 'SEO: title'), ('seo_description', 'SEO: description'), ('page_html', 'Статична сторінка'), ('news_html', 'Новина'), ('other', 'Інше')], db_index=True, max_length=32, verbose_name='Вид')),
                ('source_lang', models.CharField(default='uk', max_length=5, verbose_name='Мова джерела')),
                ('target_lang', models.CharField(default='ru', max_length=5, verbose_name='Цільова мова')),
                ('source_text', models.TextField(verbose_name='Текст джерела')),
                ('source_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хеш джерела')),
                ('target_text', models.TextField(blank=True, verbose_name='Переклад (чернетка)')),
                ('published_text', models.TextField(blank=True, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано о')),
                ('status', models.CharField(choices=[('pending', 'Очікує перекладу'), ('machine', 'Машинний, очікує схвалення'), ('approved', 'Схвалено'), ('rejected', 'Відхилено (на перепереклад)'), ('stale', 'Джерело змінилось'), ('failed', 'Валідація не пройшла'), ('skip', 'Не перекладати')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('model_note', models.TextField(blank=True, verbose_name='Примітка моделі')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Помилки валідації')),
                ('engine_model', models.CharField(blank=True, max_length=40, verbose_name='Модель')),
                ('prompt_version', models.CharField(blank=True, max_length=16, verbose_name='Версія промпта')),
                ('glossary_version', models.CharField(blank=True, max_length=16, verbose_name='Версія глосарія')),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Batch ID')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Токенів input')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Токенів output')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='Вартість, $')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Схвалено о')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Схвалив')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Тип об'єкта")),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редагував')),
            ],
            options={
                'verbose_name': 'Запис перекладу',
                'verbose_name_plural': 'Черга перекладу',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['kind', 'status'], name='tr_kind_status_idx'), models.Index(fields=['kind', 'source_hash', 'target_lang'], name='tr_memory_idx'), models.Index(fields=['status', 'kind'], name='tr_queue_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field', 'target_lang'), name='uniq_translation_target')],
            },
        ),
    ]
