# Generated by Django 5.2.16 on 2026-07-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Створено'), ('updated', 'Оновлено'), ('deactivated', 'Знято з наявності'), ('skipped', 'Пропущено'), ('duplicate_sku', 'Дубль артикула'), ('low_priority', 'SKU належить пріоритетнішому джерелу'), ('category_missing', 'Немає категорії'), ('category_remapped', 'Категорію підібрано'), ('brand_created', 'Створено бренд'), ('attr_created', 'Створено характеристику'), ('spec_filled', 'Заповнено характеристики'), ('image_failed', 'Фото не завантажилось'), ('image_purged', 'Прибрано застаріле фото'), ('price_changed', 'Змінилась ціна'), ('row_invalid', 'Невалідний рядок')], max_length=20, verbose_name='Дія'),
        ),
    ]
