# Generated by Django 5.2.16 on 2026-07-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_synclogentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieroffer',
            name='sku_is_surrogate',
            field=models.BooleanField(default=False, verbose_name='Артикул сурогатний'),
        ),
        migrations.AlterField(
            model_name='pricesheet',
            name='data_start_row',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Перший рядок даних'),
        ),
        migrations.AlterField(
            model_name='pricesheet',
            name='date_cell',
            field=models.CharField(blank=True, default='A2', max_length=8, verbose_name='Комірка з датою зрізу'),
        ),
        migrations.AlterField(
            model_name='pricesheet',
            name='header_row',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Рядок заголовків'),
        ),
        migrations.AlterField(
            model_name='pricesheet',
            name='rate_cell',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Комірка з курсом USD'),
        ),
        migrations.AlterField(
            model_name='synclogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Створено'), ('updated', 'Оновлено'), ('deactivated', 'Знято з наявності'), ('skipped', 'Пропущено'), ('incomplete', 'Неповний товар (сховано з сайту)'), ('sku_adopted', "Артикул з'явився — товар упізнано"), ('duplicate_sku', 'Дубль артикула'), ('low_priority', 'SKU належить пріоритетнішому джерелу'), ('category_missing', 'Немає категорії'), ('category_remapped', 'Категорію підібрано'), ('brand_created', 'Створено бренд'), ('attr_created', 'Створено характеристику'), ('spec_filled', 'Заповнено характеристики'), ('image_failed', 'Фото не завантажилось'), ('image_purged', 'Прибрано застаріле фото'), ('price_changed', 'Змінилась ціна'), ('row_invalid', 'Невалідний рядок')], max_length=20, verbose_name='Дія'),
        ),
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('duplicate_sku', 'Дубль артикула'), ('missing_sku', 'Немає артикула'), ('missing_photo', 'Немає фото'), ('unknown_category', 'Невідома категорія'), ('spec_not_found', 'Немає в таблиці характеристик')], db_index=True, max_length=20, verbose_name='Тип проблеми')),
                ('sheet', models.CharField(blank=True, max_length=60, verbose_name='Лист')),
                ('row_number', models.IntegerField(blank=True, null=True, verbose_name='Рядок у таблиці')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Назва товару')),
                ('message', models.TextField(blank=True, verbose_name='Що зробити')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Деталі')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='sync.syncrun', verbose_name='Прогін')),
            ],
            options={
                'verbose_name': 'Проблема в даних',
                'verbose_name_plural': 'Проблеми в даних (для замовника)',
                'ordering': ('kind', 'sheet', 'row_number', 'id'),
                'indexes': [models.Index(fields=['run', 'kind'], name='issue_run_kind_idx')],
            },
        ),
    ]
