# Generated by Django 5.2.16 on 2026-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_alter_dataissue_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataissue',
            name='kind',
            field=models.CharField(choices=[('duplicate_sku', 'Дубль артикула'), ('missing_sku', 'Немає артикула'), ('missing_photo', 'Немає фото'), ('missing_category', 'Немає категорії'), ('unknown_category', 'Невідома категорія'), ('spec_not_found', 'Немає в таблиці характеристик'), ('name_changed', 'Назву змінено в прайсі (на сайті стара)')], db_index=True, max_length=20, verbose_name='Тип проблеми'),
        ),
    ]
