# Generated by Django 5.2.16 on 2026-07-13 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay (ПриватБанк)'), ('manual', 'Ручне підтвердження'), ('mono', 'monobank (не реалізовано)')], default='liqpay', max_length=10, verbose_name='Провайдер')),
                ('reference', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Reference (order_id для LiqPay)')),
                ('provider_invoice_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ID платежу у провайдера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('created', 'Створено'), ('pending', 'Очікує'), ('held', 'Кошти заблоковано'), ('paid', 'Оплачено'), ('failed', 'Помилка'), ('reversed', 'Скасовано (сторновано)'), ('refunded', 'Повернуто'), ('expired', 'Протерміновано')], db_index=True, default='created', max_length=10, verbose_name='Статус')),
                ('paytype', models.CharField(blank=True, choices=[('card', 'Картка'), ('privat24', 'Приват24'), ('apay', 'Apple Pay'), ('gpay', 'Google Pay'), ('paypart', 'Оплата частинами (комісію платить магазин)'), ('moment_part', 'Миттєва розстрочка (відсотки платить покупець)'), ('cash', 'Готівка (термінал)'), ('invoice', 'Рахунок'), ('qr', 'QR')], db_index=True, max_length=12, verbose_name='Спосіб оплати')),
                ('installment_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість платежів')),
                ('is_moment_part', models.BooleanField(blank=True, null=True, verbose_name='Миттєва розстрочка')),
                ('receiver_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фактична комісія')),
                ('payment_url', models.URLField(blank=True, max_length=500, verbose_name='Посилання на оплату')),
                ('raw_request', models.JSONField(blank=True, default=dict, verbose_name='Запит (редаговано)')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Відповідь (редаговано)')),
                ('sender_card_mask2', models.CharField(blank=True, max_length=32, verbose_name='Маска картки')),
                ('sender_card_bank', models.CharField(blank=True, max_length=64, verbose_name='Банк-емітент')),
                ('err_code', models.CharField(blank=True, max_length=64, verbose_name='Код помилки')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Помилка')),
                ('last_end_date', models.BigIntegerField(blank=True, null=True, verbose_name='end_date останньої події')),
                ('needs_bank_review', models.BooleanField(db_index=True, default=False, verbose_name='На перевірці банку')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Діє до')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено о')),
                ('last_polled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Останнє опитування')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay (ПриватБанк)'), ('manual', 'Ручне підтвердження'), ('mono', 'monobank (не реалізовано)')], max_length=10, verbose_name='Провайдер')),
                ('invoice_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='order_id з тіла')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Статус з тіла')),
                ('body_hash', models.CharField(max_length=64, verbose_name='sha256(raw_body)')),
                ('raw_body', models.TextField(verbose_name='Сире тіло (поле data)')),
                ('signature', models.CharField(blank=True, max_length=128, verbose_name='Підпис')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Заголовки')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Розшифроване тіло')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='Підпис валідний')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Оброблено')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Оброблено о')),
                ('result', models.CharField(blank=True, choices=[('applied', 'Застосовано'), ('duplicate', 'Дубль (вже оброблено)'), ('stale', 'Застаріла подія (out-of-order)'), ('final_state', 'Стан уже фінальний'), ('amount_mismatch', 'Сума не збігається'), ('bad_signature', 'Невалідний підпис'), ('unknown_payment', 'Платіж не знайдено'), ('sandbox_in_prod', 'Sandbox-платіж у проді'), ('error', 'Помилка обробки')], max_length=16, verbose_name='Результат')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Вебхук платежу',
                'verbose_name_plural': 'Вебхуки платежів',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='pay_reconcile_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='pay_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_invoice_id', ''), _negated=True), fields=('provider', 'provider_invoice_id'), name='uniq_provider_invoice'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pay_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['processed', '-created_at'], name='webhook_unprocessed_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'body_hash'), name='uniq_webhook_body'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_id', ''), _negated=True), fields=('provider', 'invoice_id', 'status'), name='uniq_webhook_invoice_status'),
        ),
    ]
