# Generated by Django 5.2.16 on 2026-07-14 20:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Ідентифікатор сесії назовні. У API ніколи не віддаємо pk.', unique=True, verbose_name='Публічний токен')),
                ('locale', models.CharField(default='uk', max_length=5, verbose_name='Мова')),
                ('ip_hash', models.CharField(blank=True, help_text='sha256(IP + SECRET_KEY)[:32]. Сирий IP не зберігаємо.', max_length=32, verbose_name='Відбиток IP')),
                ('message_count', models.PositiveSmallIntegerField(default=0, help_text='Денормалізований лічильник: по ньому працює ліміт ASSISTANT_MAX_MESSAGES.', verbose_name='Повідомлень')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8, verbose_name='Вартість сесії, $')),
            ],
            options={
                'verbose_name': 'Сесія чату',
                'verbose_name_plural': 'Сесії чату',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['ip_hash', 'created_at'], name='asst_ip_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('assistant', 'Асистент')], max_length=10, verbose_name='Роль')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='Виклики інструментів')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Вхідні токени')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Вихідні токени')),
                ('cache_read_tokens', models.PositiveIntegerField(default=0, verbose_name='Токени з кешу')),
                ('cache_write_tokens', models.PositiveIntegerField(default=0, verbose_name='Токени в кеш')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8, verbose_name='Вартість, $')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.chatsession', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'Повідомлення чату',
                'verbose_name_plural': 'Повідомлення чату',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['session', 'created_at'], name='asst_msg_session_idx'), models.Index(fields=['created_at', 'cost_usd'], name='asst_msg_spend_idx')],
            },
        ),
    ]
