# Generated by Django 5.2.16 on 2026-07-13 13:39

import django.contrib.postgres.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=4, default=Decimal('41.5000'), max_digits=10, verbose_name='Курс USD')),
                ('usd_rate_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Курс оновлено')),
                ('usd_rate_auto_nbu', models.BooleanField(default=False, verbose_name='Тягнути курс з НБУ')),
                ('price_rounding', models.CharField(choices=[('none', 'Без округлення (до копійки)'), ('unit', 'До гривні'), ('ten', 'До 10 грн'), ('nine', 'До 9 (…99, …999)')], default='unit', max_length=6, verbose_name='Округлення ціни')),
                ('default_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('5'), max_digits=7, verbose_name='Вага за замовчуванням, кг')),
                ('default_width_cm', models.DecimalField(decimal_places=1, default=Decimal('40'), max_digits=6, verbose_name='Ширина за замовчуванням, см')),
                ('default_height_cm', models.DecimalField(decimal_places=1, default=Decimal('40'), max_digits=6, verbose_name='Висота за замовчуванням, см')),
                ('default_depth_cm', models.DecimalField(decimal_places=1, default=Decimal('40'), max_digits=6, verbose_name='Глибина за замовчуванням, см')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Синхронізація увімкнена')),
                ('sync_hours', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='Напр. 8, 12, 16, 20. Порожньо — розклад beat не чіпаємо.', size=None, verbose_name='Години запуску синку прайсу')),
                ('sync_alert_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='E-mail для алертів')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=40, verbose_name='Telegram chat_id для алертів')),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='Телефони')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адреса магазину (самовивіз)')),
                ('address_uk', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адреса магазину (самовивіз)')),
                ('address_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адреса магазину (самовивіз)')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='URL карти (embed)')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Соцмережі')),
                ('np_sender_city_ref', models.CharField(default='e221d627-391c-11dd-90d9-001a92567626', max_length=36, verbose_name='CityRef відправника (НП)')),
                ('free_shipping_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Безкоштовна доставка від, грн')),
                ('courier_uzhhorod_price_note', models.CharField(blank=True, max_length=120, verbose_name="Примітка про кур'єра по Ужгороду")),
                ('courier_uzhhorod_price_note_uk', models.CharField(blank=True, max_length=120, null=True, verbose_name="Примітка про кур'єра по Ужгороду")),
                ('courier_uzhhorod_price_note_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name="Примітка про кур'єра по Ужгороду")),
                ('payment_provider', models.CharField(default='liqpay', max_length=10, verbose_name='Платіжний провайдер')),
                ('installment_badge_text', models.CharField(blank=True, max_length=120, verbose_name='Текст бейджа «Оплата частинами»')),
                ('installment_badge_text_uk', models.CharField(blank=True, max_length=120, null=True, verbose_name='Текст бейджа «Оплата частинами»')),
                ('installment_badge_text_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Текст бейджа «Оплата частинами»')),
                ('installment_provider', models.CharField(blank=True, max_length=40, verbose_name='Банки-партнери')),
                ('installment_max_period', models.PositiveSmallIntegerField(default=24, verbose_name='Макс. платежів')),
                ('installment_min_payment', models.DecimalField(decimal_places=2, default=Decimal('300'), max_digits=10, verbose_name='Мін. платіж, грн')),
                ('hotline_enabled', models.BooleanField(default=False, verbose_name='Фід Hotline увімкнено')),
                ('hotline_firm_id', models.CharField(blank=True, max_length=20, verbose_name='Hotline firm id')),
                ('hotline_firm_name', models.CharField(blank=True, max_length=120, verbose_name='Hotline firm name')),
                ('hotline_feed_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Фід згенеровано')),
                ('ai_monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=8, verbose_name='Бюджет ШІ на місяць, $')),
                ('ai_spent_this_month_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Витрачено цього місяця, $')),
                ('default_seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO-заголовок за замовчуванням')),
                ('default_seo_title_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO-заголовок за замовчуванням')),
                ('default_seo_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO-заголовок за замовчуванням')),
                ('default_seo_description', models.CharField(blank=True, max_length=400, verbose_name='SEO-опис за замовчуванням')),
                ('default_seo_description_uk', models.CharField(blank=True, max_length=400, null=True, verbose_name='SEO-опис за замовчуванням')),
                ('default_seo_description_ru', models.CharField(blank=True, max_length=400, null=True, verbose_name='SEO-опис за замовчуванням')),
                ('default_og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG-зображення за замовчуванням')),
            ],
            options={
                'verbose_name': 'Налаштування магазину',
                'verbose_name_plural': 'Налаштування магазину',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], unique=True, verbose_name='День тижня')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Вихідний')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Відкриття')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Закриття')),
            ],
            options={
                'verbose_name': 'Графік роботи',
                'verbose_name_plural': 'Графік роботи',
                'ordering': ('weekday',),
                'constraints': [models.CheckConstraint(condition=models.Q(('is_day_off', True), models.Q(('open_time__isnull', False), ('close_time__isnull', False)), _connector='OR'), name='wh_open_day_needs_hours')],
            },
        ),
    ]
